info:
  app:
    name: ${spring.application.name}
    desc: 账户服务
    version: v1.0

spring:
  application:
    name: account

server:
  port: 8082

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'

notification.url: http://localhost:8081