info:
  app:
    name: ${spring.application.name}
    desc: 通知服务
    version: v1.0

spring:
  application:
    name: notification

server:
  port: 8081

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'


